# version: '3.8'

services:
  monitor:
    # build: .
    image: ghcr.io/itlboy/pinode-notify:latest
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - .env:/app/.env
